mentor/urls.py
#
# copyright (c) 2010 Mentortogether
#
from django.conf.urls.defaults import patterns, url
from mentortogether.mentor import views

urlpatterns = patterns('',
    url(r'^(?P<mid>\d+)/$', 
        views.mentorship, name="mentorship"),
    url(r'^(?P<mid>\d+)/profile$', 
        views.view_profile, name="view-profile"),
    url(r'^(?P<mid>\d+)/prompt/$', 
        views.prompt_listing, name="prompt-listing"),
    url(r'^(?P<mid>\d+)/prompt/(?P<pid>\d+)/start$', 
        views.prompt_start, name="prompt-start"),
    url(r'^(?P<mid>\d+)/prompt/(?P<pid>\d+)/stop$', 
        views.prompt_stop, name="prompt-stop"),
    url(r'^(?P<mid>\d+)/msg/$', 
        views.thread_listing, name="thread-listing"),
    url(r'^(?P<mid>\d+)/msg/new/(?P<pid>\d+)/$', 
        views.new_thread, name="new-thread"),
    url(r'^(?P<mid>\d+)/msg/new/( */)?$', 
        views.new_thread, name="new-thread"),
    url(r'^(?P<mid>\d+)/msg/(?P<tid>\d+)/post/$', 
        views.post_message, name="post-message"),
    url(r'^(?P<mid>\d+)/msg/(?P<tid>\d+)/$', 
        views.view_thread, name="view-thread"),
)

urls.py
from django.conf.urls.defaults import *
import mentortogether
import settings
import django.views.static
from mentortogether.user import views

# Enable Admin Interface
from django.contrib import admin
admin.autodiscover()

# FIXME: Split urls into apps

# Url Controller
urlpatterns = patterns('',

    url(r'^$', 
        view='mentortogether.views.root', name='welcome'),

    url(r'^h/$', 
        view='mentortogether.views.home', name='user-home'),

    (r'^admin/',    include(admin.site.urls)),
    (r'^u/',        include('mentortogether.user.urls')),
    (r'^m/',        include('mentortogether.mentor.urls')), 

    # mentortogether user views
    # (r'^m/(?P<username>.*)/wp/$', 'mentortogether.mentor.views.wp'),

    # (r'^m/(?P<username>.*)/archive/$',
    #     'mentortogether.mentor.views.archive_index'),

    # (r'^m/(?P<username>.*)/archive/(?P<yyyy>[0-9]+)/(?P<mm>[0-9]+)/(?P<dd>[0-9]+)$', 
    #     'mentortogether.mentor.views.archive'),
    # 
    # (r'^m/(?P<username>.*)/$', 'mentortogether.mentor.views.mentorship'),


   
    # Curriculum views
    # (r'^a/curriculum/', include('curriculum.urls')), 

    (r'^_debug/$', 'mentortogether.views.debug' ),

    # Map MEDIA_URL to MEDIA_ROOT
    (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
        django.views.static.serve, { 'document_root' : settings.MEDIA_ROOT } ),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': 'media'}),
    (r'^imgs/(?P<path>.*)$',
        django.views.static.serve, { 'document_root' : 'media/imgs' } ),
    (r'^css/(?P<path>.*)$',
        django.views.static.serve, { 'document_root' : 'media/css' } )
)

mentor/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from mentortogether.user.models import MentorApplication, MenteeApplication
from mentortogether.curriculum.models import Curriculum, CurriculumSection, CurriculumPrompt

class Project(models.Model):
    """
    Project Model
    """
    name            = models.CharField(max_length=32, blank=False)
    start_date      = models.DateField(blank=False)
    end_date        = models.DateField(blank=False)
    description     = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

class WritingPromptManager(models.Manager):
    def get_prompt_by_date(self, date):
        return self.filter(start_date__lte=date, end_date__gte=date)

class WritingPrompt(models.Model):
    """
    This model defines the set of writing prompts presented to
    mentors and mentees, within a time period. Mentors and 
    mentees have different prompts.
    """
    project         = models.ForeignKey(Project, 
                                       unique=False, 
                                       blank=False)
    title           = models.CharField(max_length=64)
    mentor_prompt   = models.TextField(blank=True)
    mentee_prompt   = models.TextField(blank=True)
    start_date      = models.DateField(blank=False, 
                                       unique=True)
    end_date        = models.DateField(blank=False, 
                                       unique=True)

    objects = WritingPromptManager()

    def __str__(self):
        return self.title

class Mentorship(models.Model):
    """
    `Mentorship` represents a Mentor-Mentee pair in the system. Each
    pair is associated with a project and a curriculum.
    """
    project    = models.ForeignKey(Project, editable=True, blank=False)
    curriculum = models.ForeignKey(Curriculum, editable=True)
    mentor     = models.ForeignKey(User, editable=True, related_name="mentorship_mentor_set")
    mentee     = models.ForeignKey(User, editable=True, related_name="mentorship_mentee_set")

    def __str__(self):
        return ("mentor: %s <-> mentee: %s" 
                    % (self.mentor.get_full_name(), 
                        self.mentee.get_full_name()))

class MessageThread(models.Model):
    """
    Message thread object, which is a set of message objects.
    """
    mentorship = models.ForeignKey(Mentorship, blank=False, editable=False)
    subject    = models.CharField(max_length=100, blank=True, editable=False)
    timestamp  = models.DateTimeField(auto_now_add=True, auto_now=True)
    prompt     = models.ForeignKey(CurriculumPrompt, null=True, blank=True)


class Message(models.Model):
    """
    Message object.
    """
    thread     = models.ForeignKey(MessageThread, null=False)
    sender     = models.ForeignKey(User, null=False, blank=False,
                                   related_name="sender_set")
    timestamp  = models.DateTimeField(auto_now_add=True, auto_now=True)
    text       = models.TextField()
    is_draft   = models.BooleanField(default=False, blank=True)
    is_unread  = models.BooleanField(default=True)


class CurriculumLog(models.Model):
    """
    A log of curriculum activity for a given `mentorship`.
    """
    prompt     = models.ForeignKey(CurriculumPrompt, blank=False)
    mentorship = models.ForeignKey(Mentorship, blank=False)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date   = models.DateTimeField(null=True, blank=True)
    remarks    = models.TextField(blank=True, null=True)
    is_active  = models.BooleanField(blank=False, null=False)

mentor/forms.py
from django import forms
from models import Message

class MessageForm(forms.ModelForm):
    def save(self, user, mobj, wp):
        m = Message(mentorship=mobj, sender=user, text=self.cleaned_data['text'])
        m.save()
        return m
        
    class Meta:
        fields = [ 'text' ]
        model = Message

mentor/views.py
from forms import MessageForm
from django import forms
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext
from datetime import date
from django.template.loader import render_to_string
from models import WritingPrompt, Project, Mentorship, Message
from mentortogether.curriculum.models import CurriculumPrompt
from mentortogether.curriculum.models import CurriculumSection
from mentortogether.mentor.models import CurriculumLog
from mentortogether.mentor.models import MessageThread
from mentortogether.mentor.models import Message
import datetime

def get_mentorship(user1, user2):
    if user1.get_profile().is_mentor() and user2.get_profile().is_mentee():
        mentor_usr, mentee_usr = (user1, user2)
    elif user2.get_profile().is_mentor() and user1.get_profile().is_mentee():
        mentor_usr, mentee_usr = (user2, user1)
    else:
        raise Http404

    mobj = Mentorship.objects.filter(mentor=mentor_usr, 
                                     mentee=mentee_usr)
    if mobj.count() < 1:
        raise Http404 
    if mobj.count() != 1:
        assert False

    return mobj[0]


def get_mentorship_objects(user):
    if user.get_profile().is_mentor():
        mobjs = Mentorship.objects.filter(mentor=user)
    elif user.get_profile().is_mentee():
        mobjs = Mentorship.objects.filter(mentee=user)
    else:
        raise Http404

    return mobjs


@login_required
def wp(request, username):

    # authorize mentor/mentee combination and get
    # mentorship object
    target_user = get_object_or_404(User, username=username)
    mobj = get_mentorship(request.user, target_user)

    # get writing prompt for today
    wp = mobj.project.writingprompt_set.get_prompt_by_date(date.today())
    if len(wp) != 1:
        raise Http404

    return render_to_response('mentorship_wp.html',
                              { 'wp' : wp[0],
                                'target_user' : target_user },
                              context_instance=RequestContext(request))

@login_required
def archive_index(request, username):
 
    target_user = get_object_or_404(User, username=username)

    # Get mentorship object for this user pair
    mobj = get_mentorship(request.user, target_user)

    wps = mobj.project.writingprompt_set.all().order_by('-start_date')

    return render_to_response('mentorship_archive_index.html',
                              { 'wps' : wps, 
                                'target_user' : target_user },
                              context_instance=RequestContext(request))

@login_required
def archive(request, username, yyyy, mm, dd):
    target_user = get_object_or_404(User, username=username)

    # Get mentorship object for this user pair
    mobj = get_mentorship(request.user, target_user)

    archive_date = date(int(yyyy), int(mm), int(dd)) 

    # Get writing prompt
    wp = mobj.project.writingprompt_set.get_prompt_by_date(archive_date)

    # Collect this weeks messages
    msgs = mobj.message_set.filter(senton__gte=wp[0].start_date)\
                .filter(senton__lte=wp[0].end_date).order_by('senton')

    msg_html = render_to_string('widgets/mentorship_msgset.html',
                                { 'msgs' : msgs,
                                  'start_date' : wp[0].start_date,
                                  'end_date'   : wp[0].end_date,
                                  'target_user': target_user })
    
    # Render messaging app
    return render_to_response('mentorship_archive.html',
                              { 'wp' : wp[0], 
                                'msg_html' : msg_html,
                                'target_user' : target_user },
                              context_instance=RequestContext(request))

def get_obj_or_none(model, **kwargs):
    try:
        return model.objects.get(**kwargs)
    except model.DoesNotExist:
        return None

def get_active_prompt(mentorship):
    """
    Returns the active prompt for a given mentorship. Returns Non
    if none.
    """
    try:
        return CurriculumLog.objects.get(mentorship=mentorship, is_active=False)
    except:
        return None

def deactivate_prompt(prompt):
    prompt.is_active = False
    prompt.save()

def get_active_log_or_none(mentorship):
    """
    Returns an active prompt for a given `Mentorship`, if there exists
    one, or returns None.
    """
    try:
        return mentorship.curriculumlog_set.get(is_active=True)
    except CurriculumLog.DoesNotExist:
        return None

def get_active_prompt_or_none(mentorship):
    try:
        return mentorship.curriculumlog_set.get(is_active=True).prompt
    except CurriculumLog.DoesNotExist:
        return None


@login_required
def prompt_start(request, mid, pid):
    mentorship = get_object_or_404(Mentorship, pk=mid)
    if get_active_log_or_none(mentorship) is not None:
        request.user.message_set.create(message="You already have an active prompt!")
    else:
        prompt = get_object_or_404(CurriculumPrompt, pk=pid)
        CurriculumLog.objects.create(mentorship=mentorship, prompt=prompt, is_active=True)
        request.user.message_set.create(message="Activated: %s" % prompt.title)
    return redirect("prompt-listing", mid=mid)


@login_required
def prompt_stop(request, mid, pid):
    mentorship = get_object_or_404(Mentorship, pk=mid)
    log = get_active_log_or_none(mentorship)
    if log and log.prompt_id != int(pid):
        return Http404
    log.is_active = False;
    log.end_date = datetime.datetime.now()
    log.save()
    return redirect("prompt-listing", mid=mid)


def get_target_user(user, mentorship):
    if user.id == mentorship.mentor_id:
        return mentorship.mentee
    if user.id == mentorship.mentee_id:
        return mentorship.mentor
    raise Exception("bug")

def get_mentorship_context(request_user, mid):
    mentorship = get_object_or_404(Mentorship, pk=mid)
    target_user = get_target_user(request_user, mentorship)
    context = {}
    context['role'] = request_user.get_profile().role
    context['mentorship'] = mentorship
    context['target_user'] = target_user
    context['prompt'] = get_active_prompt_or_none(mentorship)
    return context

@login_required
def thread_listing(request, mid):
    """
    List message threads for the given mentorship
    """
    context = get_mentorship_context(request.user, mid)
    template = 'mentor/thread_listing.html'
    mentorship = context['mentorship']
    threads = mentorship.messagethread_set.all().order_by('-timestamp')
    annotated_threads = []
    for thread in threads:
        count  = ( thread.message_set.count() )
        unread  = ( thread.message_set
                        .filter(is_unread=True)
                        .exclude(sender=request.user)
                        .count() )
        annontated_threads.append({ "obj": thread, "count": count, "unread": unread })
    context["threads"] = threads
    context["annotated_threads"] = annotated_threads
    return render_to_response(template, context, RequestContext(request))


@login_required
def prompt_listing(request, mid):
    """
    List all available writing prompts for a given mentorship.
    Only a mentor can make such a selection.
    """
    # Only mentors can access this.
    if not request.user.get_profile().is_mentor():
        return redirect("mentorship", mid=mid)

    mentorship = get_object_or_404(Mentorship, pk=mid)
    target_user = get_target_user(request.user, mentorship)
    context = {}
    template = 'mentor/prompt_select.html'
    context['mentorship'] = mentorship
    context['target_user'] = target_user

    # Collate bits of information about curriculum nodes, for the
    # given mentorship.
    nodes = []
    for section in mentorship.curriculum.get_active_sections():
        nodes.append({ 'section' : section })
        for prompt in section.get_active_prompts():
            log = get_obj_or_none(CurriculumLog, mentorship=mentorship, 
                                                 prompt=prompt,
                                                 is_active=True)
            nodes.append({ 'log' : log, 'prompt' : prompt })
    context['nodes'] = nodes

    return render_to_response(template, context, RequestContext(request))

@login_required
def view_thread(request, mid, tid):
    context = get_mentorship_context(request.user, mid)
    thread = get_object_or_404(MessageThread, pk=tid, mentorship=context['mentorship'])
    messages = Message.objects.filter(thread=thread).order_by('timestamp')

    # Marking threads as read.
    ( thread.message_set
        .filter(is_unread=True)
        .exclude(sender=request.user)
        .update(is_unread=False) )

    context['thread'] = thread
    context['thread_msgs'] = messages
    template = 'mentor/view_thread.html'

    return render_to_response(template, context, RequestContext(request))

@login_required
def post_message(request, mid, tid):
    if request.method != 'POST':
        raise Http404
    if ('text' not in request.POST) or (len(request.POST['text']) == 0):
        raise Http404
    context = get_mentorship_context(request.user, mid)
    mentorship = context['mentorship']
    thread = mentorship.messagethread_set.get(pk=tid)
    thread.message_set.create(sender=request.user, text=request.POST['text'])
    request.user.message_set.create(message="Message posted.")
    return redirect("view-thread", mid=mid, tid=thread.id)
        

@login_required
def new_thread(request, mid, pid=None):
    """
    Starts a new messaging thread.
    """
    context = get_mentorship_context(request.user, mid)
    template = 'mentor/new_thread.html'
    mentorship = context['mentorship']

    # Selected writing prompt
    prompt = None
    if pid is not None:

mentor/templates/mentor/dashboard.html
{# Dashboard view for a given mentorship pair #}

{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}

   {{ block.super }}

   <table cellspace="2">
      <tr>
        <td class='field_name'>Name</td>
        <td class='field_value'>
          {{ target_user.first_name|capfirst }} {{ target_user.last_name|capfirst }}
        </td>
      </tr>
      {% ifequal target_role "mentor" %}
      <tr>
        <td class='field_name'>Occupation</td>
        <td class='field_value'>
          {{ target_app.curr_occup_title|capfirst }}, 
          {{ target_app.curr_occup_co|capfirst }},<br/>
          ({{ target_app.curr_occup_func|capfirst }}; 
           {{ target_app.curr_occup_industry }})</td>
      </tr>
      {% else %}
      <tr>
        <td class='field_name'>Grade</td>
        <td class='field_value'>{{ target_app.grade }} <br/>
      </tr>
      <tr>
        <td class='field_name'>School</td>
        <td class='field_value'>{{ target_app.school|capfirst }} <br/>
      </tr>
      {% endifequal %}
      <tr>
          <td colspan="2">
            <span style="font-weight: bold">
                ( <a href="{% url view-profile mentorship.id %}">view full profile</a> )
            </span>
          </td>
      </tr>
    </table>

    <div class="discussions">
        <h3>Messaging</h3>
        {# if this is a mentor, new discussion starts with the selection of a prompt #}
        {% ifequal role 'mentor' %}
            <a href="{% url prompt-listing mentorship.id %}">Start New Discussion</a>
        {% else %}
            <a href="{% url new-thread mentorship.id %}">Start New Discussion</a>
        {% endifequal %}
        <br/>
        <div id="thread-listing">
            <table>
                <thead>
                    <tr> 
                        <th class="col-subject">Subject</th>
                        <th class="col-date" colspan="2">Last Activity</th>
                    </tr>
                </thead>
                <tbody>
                    {% for thread in annotated_threads %}
                    <tr class="{% if thread.unread %}highlight{% endif %}">
                            <td class="col-first">
                                <a href="{% url view-thread mentorship.id thread.obj.id %}">{{ thread.obj.subject }}</a> ({{thread.count}})
                                <div class="prompt">{{ thread.obj.prompt.title }}</div></td>
                            </td>
                            <td>{{ thread.obj.timestamp|date:"H:i" }}</td>
                            <td class="col-last">{{ thread.obj.timestamp|date:"jS M y" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="col-first">
                                You have no messages. :-(
                            </td>
                            <td class="col-last">&nbsp;</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

mentor/templates/mentor/mailbox.html
{% extends 'mentorship.html' %}

{% block secondary_title %}
    {{ user.first_name|capfirst }} {{ user.last_name|capfirst }} | Mentor
{% endblock %}

{% block secondary_header %}
    {{ user.first_name|capfirst }} {{ user.last_name|capfirst }} | Mentor
{% endblock %}

{% block content_col %}
    {% if not prompt %}
        {% if target_user.get_profile.is_mentor %}
            <div>
                You have not selected a writing prompt.
                <a href="{% url select-prompt mentorship.id %}">Select A Writing Prompt</a>
            </div>
    {% endif %}
{% endblock %}

mentor/templates/mentor/mentorship.html
{% extends 'site/layout_2col.html' %}

{% block PrimaryContent %}

    {{ block.super }}

    <div id="mentorship-main">
        {% block Mentorship %}{% endblock %}
    </div>

{% endblock %}

{% block SecondaryContent %}
    <div id="mentorship">
       <div id="target-user-info">
            <div class="photo">
                <img src="{% url user-photo-image uid=target_user.id image_type='profile' %}" />
            </div>
            <div class="stats">
                <ul class="menu-list">
                    <li><a href="{% url mentorship mentorship.id %}">{{ target_user.first_name|capfirst }} {{ target_user.last_name|capfirst }}</a></li>
                </ul>
            </div>
        </div>

        <hr size="1" />
        <div>
        <ul class="menu-list">
            <li><a href="{% url mentorship mentorship.id %}">Messaging</a></li>
        </ul>
        </div>

    </div>
{% endblock %}

mentor/templates/mentor/new_message.html
{% extends 'mentorship.html' %}

{% block secondary_title %}
    New Message
{% endblock %}

{% block secondary_header %}
    New Message
{% endblock %}

{% block content_col %}
    {% for node in nodes %}
        {% if node.section %}
            <div class="section">
                {{ node.section.title }}
                {{ node.section.summary }}
            </div>
        {% endif %}
        {% if node.prompt %}
            <div class="prompt">
                {{ node.prompt.title }}
                {{ node.prompt.summary }}
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

mentor/templates/mentor/new_thread.html
{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}

    {% if prompt %}
        <div class="clearfix span-14 last">
            <div id="writing-prompt">
                <div style="font-weight: bold; margin-bottom: 10px; font-size: 1.1em;">{{ prompt.title }}</div>
                {{ prompt.mentor_doc }}
            </div>
        </div>
    {% endif %}

    <div id="message-thread">
        <ul>
            <li class="clearfix">
                <div class="span-2">
                    <div class="sender-photo" 
                         style="background-image: url('{% url user-photo-image uid=user.id image_type="tag" %}');">
                    </div>
                </div>
                <div class="span-12 last">
                    <form method="post" action="{% url new-thread mentorship.id prompt.id %}">
                        <div class="xxmessage-subject">
                            Subject: <br/>
                            <input id="id_subject" "type="text" name="subject" /> 
                        </div>
                        <div>
                            Message: <br/>
                            <textarea id="id_text" class="span-12 last" name="text"></textarea>
                            <input type="submit" value="Post" />
                        </div>
                    </form>
                </div>
            </li>
        </ul>
    </div>

{% endblock %}

mentor/templates/mentor/profile_view.html
{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}
    
  {{ block.super }}

  <table cellspace="2">
    <tr>
      <td class='field_name'>Name</td>
      <td class='field_value'>
        {{ target_user.first_name|capfirst }} {{ target_user.last_name|capfirst }}
      </td>
    </tr>
    {% ifequal target_role "mentor" %}
    <tr>
      <td class='field_name'>Occupation</td>
      <td class='field_value'>
        {{ target_app.curr_occup_title|capfirst }}, 
        {{ target_app.curr_occup_co|capfirst }},<br/>
        ({{ target_app.curr_occup_func|capfirst }}; 
         {{ target_app.curr_occup_industry }})</td>
    </tr>
    {% else %}
    <tr>
      <td class='field_name'>Grade</td>
      <td class='field_value'>{{ target_app.get_grade }} <br/>
    </tr>
    <tr>
      <td class='field_name'>School</td>
      <td class='field_value'>{{ target_app.school|capfirst }} <br/>
    </tr>
    {% if target_app.preuniv_interest %}
        <tr>
            <td class='field_name'>Pre-Univ Interest</td>
            <td class='field_value'>{{ target_app.preuniv_interest|capfirst }}
        </tr>
    {% endif %}
    {% if target_app.puc_course %}
        <tr>
            <td class='field_name'>PUC Course</td>
            <td class='field_value'>{{ target_app.puc_course|capfirst }}
        </tr>
    {% endif %}
    {% if target_app.degree_course %}
        <tr>
            <td class='field_name'>Degree Course</td>
            <td class='field_value'>{{ target_app.degree_course|capfirst }}
        </tr>
    {% endif %}
    {% if target_app.subjects %}
        <tr>
            <td class='field_name'>Subjects</td>
            <td class='field_value'>{{ target_app.subjects|capfirst }}
        </tr>
    {% endif %}
    <tr>
        <td class='field_name'>Languages</td>
        <td class='field_value'>{{ target_app.languages }}
    </tr>
    {% if target_app.career1 %}
        <tr>
            <td class='field_name'>Career Interest #1</td>
            <td class='field_value'>{{ target_app.career1 }}
        </tr>
    {% endif %}
    {% if target_app.career2 %}
        <tr>
            <td class='field_name'>Career Interest #2</td>
            <td class='field_value'>{{ target_app.career2 }}
        </tr>
    {% endif %}
    {% if target_app.career3 %}
        <tr>
            <td class='field_name'>Career Interest #3</td>
            <td class='field_value'>{{ target_app.career3 }}
        </tr>
    {% endif %}
    {% if target_app.career4 %}
        <tr>
            <td class='field_name'>Career Interest #4</td>
            <td class='field_value'>{{ target_app.career4 }}
        </tr>
    {% endif %}
    {% if target_app.career5 %}
        <tr>
            <td class='field_name'>Career Interest #5</td>
            <td class='field_value'>{{ target_app.career5 }}
        </tr>
    {% endif %}
    {% if target_app.mentor_role1 %}
        <tr>
            <td class='field_name'>Mentor Role #1</td>
            <td class='field_value'>{{ target_app.mentor_role1 }}
        </tr>
    {% endif %}
    {% if target_app.mentor_role2 %}
        <tr>
            <td class='field_name'>Mentor Role #2</td>
            <td class='field_value'>{{ target_app.mentor_role2 }}
        </tr>
    {% endif %}
    {% if target_app.mentor_role3 %}
        <tr>
            <td class='field_name'>Mentor Role #3</td>
            <td class='field_value'>{{ target_app.mentor_role3 }}
        </tr>
        {% endif %}
  {% endifequal %}
  </table>

{% endblock %}

mentor/templates/mentor/prompt_select.html
{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}
    
    {{ block.super }}

    <h2>Select a Writing Prompt</h2>

    <p>Select a writing prompt that will provide you and your mentee 
    with a topical guide for your dicussions.</p>

    <p><a href="{% url new-thread mentorship.id %}">Skip this step</a></p>

    <div id="prompt-listing">
        {% for node in nodes %}

            {% if node.section %}
                <div class="section">
                    <div class="title">
                        {{ node.section.title }}
                    </div>
                    <div class="summary">
                        {{ node.section.summary }}
                    </div>
                </div>
            {% endif %}

            {% if node.prompt %}
                <div class="prompt {% if node.log.is_active %}active-prompt{% endif %}">
                    <div class="title">
                        {{ node.prompt.title }}
                    </div>
                    <div class="summary">
                        {{ node.prompt.summary }}
                    </div>
                    <form action="{% url new-thread mentorship.id node.prompt.id %}" 
                          method="get">
                        <input type="submit" value="Select" />
                    </form>
                </div>
            {% endif %}

        {% endfor %}
    </div>

{% endblock %}

mentor/templates/mentor/thread_listing.html
{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}
    
    {{ block.super }}

    <div id="thread-listing">
        <a href="{% url new-thread mentorship.id %}">Start New Discussion</a>

        <table>
            {% for thread in threads %}
                <tr>
                    <td>
                        <a href="{% url view-thread mentorship.id thread.id %}">{{ thread.subject }}</a></td>
                    <td>{{ thread.timestamp }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

mentor/templates/mentor/view_thread.html
{% extends 'mentor/mentorship.html' %}

{% block Mentorship %}

    {% if thread.prompt %}
        <div class="clearfix span-14 last">
            <div class="line-format" style="font-weight: bold; margin-bottom: 10px; font-size: 1.1em;">{{ thread.prompt.title }}</div>
            <div class="line-format" id="writing-prompt">{{ thread.prompt.mentor_doc }}</div>
        </div>
    {% endif %}

    <div id="message-thread">
        <ul>
            {% for msg in thread_msgs %}
            <li class="clearfix">
                <div class="span-2">
                    <div class="sender-photo" 
                         style="background-image: url('{% url user-photo-image uid=msg.sender.id image_type="tag" %}');">
                    </div>
                </div>
                <div class="span-12 last">
                    {% if forloop.first %}
                        <div class="message-subject">{{ thread.subject }}</div>
                    {% endif %}
                    <div class="message-text">{{ msg.text }}</div>
                </div>
            </li>
            {% endfor %}
            <li class="clearfix">
                <div class="span-2">
                    <div class="sender-photo" 
                         style="background-image: url('{% url user-photo-image uid=user.id image_type="tag" %}');">
                    </div>
                </div>
                <div class="span-12 last">
                    <form action="{% url post-message mentorship.id thread.id %}" method="post">
                        <textarea id="id_text" class="span-12 last" name="text"></textarea>
                        <input type="submit" value="Post" />
                    </form>
                </div>
            </li>
        </ul>
    </div>

{% endblock %}